Repository Androz2091/discord-giveaways, pull requests merged in 2021-02, with the labels that each got.

#203 🐛 Bugfix and improve roll and reroll function
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
Labels: bug, improvement

#45 "Last Chance to enter" embed
  src/Constants.js
  src/Manager.js
Labels: enhancement

#211 🏷️ Update data types
  examples/custom-databases/mongoose.js
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
  typings/index.d.ts
Labels: documentation, improvement, related to examples

#195 ✨ Bugfix/quickmongo | Manager starts too early/DB is not fast enough
  README.md
  examples/custom-databases/quickmongo.js
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
Labels: bug, improvement, related to examples

#187 ✨ Bonus Entries
  README.md
  examples/custom-databases/mongoose.js
  package.json
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
  typings/index.d.ts
Labels: enhancement

#219 ✨ Add warning to README
  README.md
Labels: documentation, related to examples
