Repository Androz2091/discord-giveaways, pull requests merged in 2021-06, with the labels that each got.

#307 ✨ Add thumbnail support and use setTitle instead of setAuthor
  README.md
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
  typings/index.d.ts
Labels: enhancement, improvement

#295 ✨ style(*): Fix JSDoc spelling errors, and more.
  README.md
  src/Constants.js
  src/Giveaway.js
Labels: documentation

#269 ✨Ability to pause/unpause giveaways
  README.md
  examples/custom-databases/mongoose.js
  examples/simple.js
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
  typings/index.d.ts
Labels: enhancement
