Repository Androz2091/discord-giveaways, pull requests merged in 2021-08, with the labels that each got.

#303 ✨ end function, noWinnerMessage option
  README.md
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
  typings/index.d.ts
Labels: improvement

#358 ✨ Use discord timestamps
  README.md
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
  typings/index.d.ts
Labels: improvement

#318 🐛 allowedMentions
  examples/custom-databases/mongoose.js
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
  typings/index.d.ts
Labels: enhancement

#344 ✨ Apache CouchDB - Nano example
  README.md
  examples/custom-databases/nano.js
Labels: related to examples

#302 :sparkles: Access any giveaway property in giveaway messages
  README.md
  examples/custom-databases/mongoose.js
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
  typings/index.d.ts
Labels: enhancement, improvement

#224 ✨Drops feature
  examples/custom-databases/mongoose.js
  src/Constants.js
  src/Giveaway.js
  src/Manager.js
  typings/index.d.ts
Labels: enhancement
